spring.application.name=learn-springboot-28minute
management.endpoints.jmx.exposure.include=*
management.endpoints.web.exposure.include=*

#Database
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test_db
spring.datasource.url=jdbc:h2:file:D:/workspaces/learn-springboot-28minute/src/main/resources/data/course_demo;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=
#spring.sql.init.mode=always
spring.jpa.show-sql=true


currency-service.url=http://localhost:8000
currency-service.username=user
currency-service.key=password


