spring.application.name=learn-springboot-28minute
#logging.level.org.springframework=debug
spring.profiles.active=dev

spring.mvc.view.prefix= /WEB-INF/views/
spring.mvc.view.suffix= .jsp

spring.mvc.format.date=yyyy-MM-dd
